[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glamour = "0.8.0"
indicatif = { version = "0.17.6", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.7.0"
